---
name: 'Linguist Action (Deprecated)'
description: 'This action detects language type for a file, or, given a repository, determine language breakdown in JSON format.'
branding:
  icon: eye-off
  color: gray-dark
inputs:
  path:
    description: 'Path to the repository'
    required: false
    default: './'
  percentage:
    description: 'Output will be in percentage format, e.g. {"Python":"100%"}. By default it is in fractions, e.g. {"Python":1.0}. Default: false.'
    required: false
    default: "false"
outputs:
  data:
    value: ""
    description: 'Result of the output'
runs:
  using: "composite"
  steps:
    - run: echo "::warning::This GitHub action is deprecated and is no longer maintained. Please use https://github.com/fabasoad/setup-enry-action instead"
      shell: sh
