name: Dockerfile Lint

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: ./
          HADOLINT_ACTION_COMMENT: false
